from arbi.constants import VERSION


TC_TOOL_VER = '0.13.5 - ' + VERSION

VIP_MATCH_ID_MAPPING_BASE_URL = 'http://14.102.249.58/admin/api/getvipmatchid'
SCRAPER_TIMEOUT = 30
SCRAPER_RUNNING_INTERVAL = 6
SPORTTERY_DATA_FORCE_SEND_INTERVAL = 60 * 3
LOG_MEMORY_INTERVAL = 60 * 5

LOG_UNKNOWN_MATCH_ID_FREQUENCY = 60 * 10
LOG_MEMORY_FREQUENCY = 60 * 3
MAX_SOURCE_QUEUE_SIZE = 40000
SOURCE_QUEUE_CLEARANCE_SIZE = 30000
